-- -----------------------------------------------------------------------------
-- SQLite Schema for CamThink Wiki Ask AI Feature
-- Alternative schema for environments using SQLite instead of PostgreSQL
-- -----------------------------------------------------------------------------

-- SQLite doesn't support UUID natively, use TEXT with UUID generation in app layer
-- SQLite doesn't have CHECK with IN for all versions, using TEXT with app validation

-- -----------------------------------------------------------------------------
-- Session tracking
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_sessions (
    id TEXT PRIMARY KEY,                -- UUID generated by application
    user_ip_hash TEXT NOT NULL,         -- Anonymized daily hash for privacy
    language TEXT DEFAULT 'en',         -- 'en' or 'zh-Hans'
    created_at TEXT DEFAULT (datetime('now'))  -- ISO 8601 timestamp
);

CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_ip_hash ON chat_sessions(user_ip_hash);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_created_at ON chat_sessions(created_at DESC);

-- -----------------------------------------------------------------------------
-- Message history
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_messages (
    id TEXT PRIMARY KEY,                -- UUID generated by application
    session_id TEXT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role TEXT NOT NULL,                 -- 'user' or 'assistant'
    content TEXT NOT NULL,
    sources TEXT,                       -- JSON string of source references
    metadata TEXT,                      -- JSON string of metadata
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ON chat_messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_role ON chat_messages(role);

-- -----------------------------------------------------------------------------
-- User feedback
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_feedback (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id TEXT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    rating TEXT NOT NULL,               -- 'positive' or 'negative'
    comment TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_chat_feedback_message_id ON chat_feedback(message_id);
CREATE INDEX IF NOT EXISTS idx_chat_feedback_rating ON chat_feedback(rating);
CREATE INDEX IF NOT EXISTS idx_chat_feedback_created_at ON chat_feedback(created_at DESC);

-- -----------------------------------------------------------------------------
-- Document indexing state management
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS document_index_status (
    file_path TEXT PRIMARY KEY,         -- e.g. "docs/1-neoedge/intro.md"
    content_hash TEXT NOT NULL,         -- MD5/SHA256 of file content
    last_indexed_at TEXT DEFAULT (datetime('now')),
    status TEXT NOT NULL,               -- 'pending', 'indexed', 'failed', 'deleted'
    error_message TEXT,                 -- Error details if failed
    chunk_count INTEGER DEFAULT 0,      -- Number of chunks created
    language TEXT DEFAULT 'en'          -- 'en' or 'zh-Hans'
);

CREATE INDEX IF NOT EXISTS idx_document_index_status_status ON document_index_status(status);
CREATE INDEX IF NOT EXISTS idx_document_index_status_last_indexed_at ON document_index_status(last_indexed_at DESC);
CREATE INDEX IF NOT EXISTS idx_document_index_status_language ON document_index_status(language);

-- Note: Vector embeddings for SQLite require sqlite-vec extension
-- See: https://github.com/asg0r/sqlite-vec
-- For production, use PostgreSQL with pgvector or Qdrant

-- -----------------------------------------------------------------------------
-- Cleanup function (to be called from application)
-- -----------------------------------------------------------------------------
-- DELETE FROM chat_sessions WHERE datetime(created_at) < datetime('now', '-30 days');
